server:
  port: 9090
spring:
  cloud:
   gateway:
    routes:
      - id: api1_hello
        uri: 'http://localhost:8081'
        predicates:
          - Path=/
          - Query=v,1
      - id: api2_hello
        uri: 'http://localhost:8082'
        predicates:
          - Path=/
          - Query=v,2
